services:
  client:
    build:
      context: ./client
    container_name: client_container
    ports:
      - ${CL_PORT}:${CL_PORT} 
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      APP_ENV: ${APP_ENV}  
      SRV_PROTOCOL: ${SRV_PROTOCOL} 
      SRV_IP: ${SRV_IP} 
      SRV_PORT: ${SRV_PORT}      

  server:
    build:
      context: ./server
    container_name: server_container
    ports:
      - ${SRV_PORT}:${SRV_PORT} 
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./server/api/v1/uploads:/app/uploads  
    environment:
      APP_ENV: ${APP_ENV}  
      SRV_PROTOCOL: ${SRV_PROTOCOL} 
      SRV_IP: ${SRV_IP} 
      SRV_PORT: ${SRV_PORT} 
      DB_USER: ${DB_USER} 
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_IP: ${DB_IP} 
      DB_PORT: ${DB_PORT} 
      DB_NAME: ${DB_NAME}
      SENDGRID_API_KEY: "${SENDGRID_API_KEY}" 

  db:
    image: postgres:17
    container_name: postgres_container
    environment:
      POSTGRES_USER: theo
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: user_db
    ports:
      - ${DB_PORT}:${DB_PORT} 
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
