services:
  client:
    build:
      context: ./client
    container_name: client_container
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
      APP_ENV: ${APP_ENV}       


  server:
    build:
      context: ./server
    container_name: server_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./server/api/v1/uploads:/app/uploads  
    environment:
      APP_ENV: ${APP_ENV}  
      SRV_PROTOCOL: ${SRV_PROTOCOL} 
      SRV_IP: ${SRV_IP} 
      SRV_PORT: ${SRV_PORT} 
      DB_USER: ${DB_USER} 
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_IP: ${DB_IP} 
      DB_PORT: ${DB_PORT} 
      DB_NAME: ${DB_NAME} 

  db:
    image: postgres:17
    container_name: postgres_container
    environment:
      POSTGRES_USER: theo
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
