services:
  client:
    build:
      context: ./client
    container_name: client_container
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  

  server:
    build:
      context: ./server
    container_name: server_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./server/api/v1/uploads:/app/uploads  

  db:
    image: postgres:17
    container_name: postgres_container
    environment:
      POSTGRES_USER: theo
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
