// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	User    *User   `json:"user"`
	Token   string  `json:"token"`
	Message *string `json:"message,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID          string  `json:"id"`
	Username    string  `json:"username"`
	Email       string  `json:"email"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	CreatedAt   string  `json:"createdAt"`
}
